### ISSUE TITLE
リソースを yaml 化する

### ISSUE THREAD

**Issue by osyo-manga** [vim-jp/reading-vimrc#6]
いまは手動で markdown を作成、編集を行っていますが、アーカイブなどのデータを yaml 化してなるべく自動で生成するようにしたい。
最終的にはその回の情報を載せた archiveXXX.yml と次の回の情報を載せた next.yml みたいなのを追加、編集すれば更新作業が完了する形に持って行きたいと考えています。

**Comment by haya14busa** [comment]
一応現在のVimプラグイン読書会の情報: https://github.com/haya14busa/reading-vimplugin/tree/gh-pages/_data

**Comment by osyo-manga** [comment]
Lingrのログ:http://lingr.com/room/vim/archives/2014/02/15#message-18360036

**Comment by osyo-manga** [comment]
現在の更新作業一覧
- `index.md` の次回の予定を編集
- `archive/XXX.md` を追加
- `archive/index.md` に `archive/XXX.md` の追加
- [wiki](https://github.com/vim-jp/reading-vimrc/wiki/Request)から該当する vimrc を削除

他、抜けている作業があればコメント下さい。

**Comment by osyo-manga** [comment]
とりあえずの作業場という事で fork しました
https://github.com/osyo-manga/reading-vimrc
作業したいという方は Collaborators に追加するので教えてください。

**Comment by osyo-manga** [comment]
実装する作業内容
- `next.yml` を追加
- `next.yml` の内容を `index.md` から参照する
- `archive/index.md` から `archive/XXX.yml` が参照されるような形にする
  - ただし、現状の ``archive/XXX.md` を `yml` にコンバートするのは後回しで処理を追記する感じで

**Comment by haya14busa** [comment]
進捗どうですか(どこを作業しているとか教えてもらえれば僕ある程度やりますよ)

**Comment by osyo-manga** [comment]
ｳｯ､少し作業していたんですがまだほとんど手を付けられていない状態です…。
余裕ありそうであれば @haya14busa さんの方で作業してもらったほうがよいかも。

**Comment by haya14busa** [comment]
了解です。じゃあやっておきますです！

**Comment by osyo-manga** [comment]
おねがいしまする。

**Comment by haya14busa** [comment]
`_data/next.yml`に対応ed

これで`_data/next.yml`を編集すると勝手に`index.md`が更新されます。

Lingr-botの方で`_data/next.yml`から情報とってきて自動postとかは任せます

**Comment by haya14busa** [comment]
(作業場とissueの場所が違ってちょっと面倒感)

せっかくforkしてるので、https://github.com/osyo-manga/reading-vimrc こっちもgh-pagesを有効化すると良さげな気がします。

コンテンツかぶってグーグルさんに怒られるかもということで有効化しないなら、やっぱりこっちのbranchで作業すれば良い感ありますからね

**Comment by haya14busa** [comment]
`_data/archive/1.yml`のように(少なくとも素の)Jekyllでは`_data/`下にディレクトリをおいてデータにアクセスするということができないようです。

ですので
1. `_data/archive001.yml`という形式でどんどん`_data/`ディレクトリ下につっこむ
2. `_data/archives.yml` の1ファイルに追記する形にする

という2通りの選択肢になるかと思います。

1は更新作業するのは楽ですが、`_data/next.yml`も含め、せっかくほかのデータもおいておけるのに`_data`ディレクトリが`_data/archiveXXX.yml`というファイルで溢れかえります。

2は更新作業がファイルの追加->ファイルへの追記となり少々面倒になりますが、`_data`ディレクトリは汚れないし、1ファイルに纏まっているので自動化の作業がしやすい,あとでデータを見返したり、再利用するときなどにも纏まっていてちょっと楽というメリットがあるかなと思います。

また http://lingr-bot-readingvimrc.herokuapp.com/reading_vimrc/vimplugin/yml のvimrc版ができれば

```
curl http://lingr-bot-readingvimrc.herokuapp.com/reading_vimrc/vimrc/yml >> _data/archives.yml
```

このようにリダイレクトで追記しちゃえばワンコマンドで更新できる(はず)なのでそこまで追記でも手間じゃないかなぁーと思います。

というか本音はファイル分けてたら自動化対応するのが面倒くさいというやつです。

どうですかね?

**Comment by haya14busa** [comment]
返事を聞く前に`_data/archives.yml`に統一する形で実装しちゃいました

[_data/archives.yml](https://github.com/osyo-manga/reading-vimrc/blob/gh-pages/_data/archives.yml)

``` yaml
- id: 86
  date: 2014-02-22 23:00
  author:
    name: haya14busa
    url: https://github.com/haya14busa
  vimrcs:
    - name: vimrc
      url: https://github.com/haya14busa/dotfiles/blob/be8937e097af4666a4057090b79792acc137fca1/.vimrc
    - name: gvimrc
      url: https://github.com/haya14busa/dotfiles/blob/be8937e097af4666a4057090b79792acc137fca1/.gvimrc
  part: 後編 # 省略可
  members:
    - Lindan
    - deris0126
    - haya14busa
    - hotoolong
    - lisia
    - manga_osyo
    - mattn
    - raa0121
    - rbtnn
    - thinca
  log: http://lingr.com/room/vim/archives/2014/02/15#message-18358061
  links:
    - http://chopapp.com/#ebxfqbi
  other: 何か特記事項があればここに書ける。<br>
         ただ直接XXX.mdを編集したほうがよさげか
```

こんな感じで書けば`archives/index.md`の一覧ページも勝手に変わるようなっています。

また`archives/XXX.md`の各回のmarkdownファイルについては

https://github.com/osyo-manga/reading-vimrc/blob/gh-pages/archive/086.md

ここの回数である`86`をその回数に合わせたものを用意するだけでOKとなります。また`ダウンロード`リンクといったGitHub特有のものは対応させています。BitBucketとかその他はとりあえず知らない。

自動生成するスクリプトとか書いていませんが、http://lingr-bot-readingvimrc.herokuapp.com/reading_vimrc/vimrc/markdown これを上記の[これ](https://github.com/osyo-manga/reading-vimrc/blob/gh-pages/archive/086.md)の86の部分を動的に開催数に変換するものを用意すれば

```
curl http://lingr-bot-readingvimrc.herokuapp.com/reading\_vimrc/vimrc/markdown > \_data/XXX.md
```

これだけで済むかもですね。まぁ明らかにローカルでもできるのでｱﾚですが。

あと全体を通して`vimrc`は複数対応し、`author`は流石にプラグイン読書会と違って2人以上になることはないはずなので基本authorは1人だけ対応しています。

また`_data/next.yml`は最新(というか普通)のvimrcへのリンクを書いているのに対し、`_data/archives.yml`はsha-1を含めたURLしか書いていません。プラグインと違ってリポジトリ中の1ファイルを参照するので正規表現が使えない状態でうまく対応するのが面倒くさかった...面倒なだけで、頑張れば普通のurlとhashで生成できるかもしれませんが今のところ使われていないっぽいので。

そんなかんじです。

**Comment by osyo-manga** [comment]
@haya14busa ++

> せっかくforkしてるので、https://github.com/osyo-manga/reading-vimrc こっちもgh-pagesを有効化すると良さげな気がします。

http://osyo-manga.github.io/reading-vimrc/ にアクセスできると思うのですが、そういうことではなくて？

> _data/archive/1.ymlのように(少なくとも素の)Jekyllでは_data/下にディレクトリをおいてデータにアクセスするということができないようです。

手段としての提案なのですが、 `_data/archive/1.yml` ではなくて `_archive/1.yml` とするのはどうでしょうか（技術的にできるかわかりませんが…。
ただ、

> 2._data/archives.yml の1ファイルに追記する形にする

の方が自動化がやりやすいというのであればこちらでもよいと思います。
ここら辺は実際に更新作業している方（@thinca, @deris）の意見を聞いてみたいですね。
更新作業の流れは

1.`_data/next.yml` に次回の予定を記述する
2.`_data/archives.yml` にその回の情報を追記する
3.`archives/XXX.md` を追加する

という認識であっていますか？

**Comment by haya14busa** [comment]
> http://osyo-manga.github.io/reading-vimrc/ にアクセスできると思うのですが、そういうことではなくて？

are...アクセスできる...さっき試した時どこかurl間違っていたようです()

> 手段としての提案なのですが、 `_data/archive/1.yml` ではなくて `_archive/1.yml` とするのはどうでしょうか（技術的にできるかわかりませんが…。

これは残念ながら(少なくとも素の)Jekyllでは無理ですね。不便。

> 2.`_data/archives.yml` の1ファイルに追記する形にする
> の方が自動化がやりやすいというのであればこちらでもよいと思います。

過去の開催の一覧でループを回さないといけないので、`_data/`下のファイルをループ回していらない`_data/next.yml`などを取り除くなど無駄な作業が発生してつらみがあるので2押しです。

> 更新作業の流れは
> 
> 1._data/next.yml に次回の予定を記述する
> 2._data/archives.yml にその回の情報を追記する
> 3.archives/XXX.md を追加する
> 
> という認識であっていますか？

はい。

1はともかく2と3はシェルスクリプトか、LLか、Vim scriptか()でいい感じのスクリプトを作れば同時に出来そうですね。
そういうのがアレばファイル追加->追記による面倒さはほぼ解消されると思われまするです。

**Comment by haya14busa** [comment]
ワンコマンドで2と3をやってくれるアップデートスクリプト(かなりｱﾚかもだけど)一応書きました。おしょーさんのherokuのvimrc botで使われているvimプラグインのyamlのやつがvimrc版もできるという想定で書いたので下記の様にしてほしいです @osyo-manga 

http://lingr-bot-readingvimrc.herokuapp.com/reading_vimrc/vimrc/yml
上記のURLに以下のように情報を載せてもらえるようにできれば完璧です。

```
- id: 86
  date: 2014-03-01 23:00
  author:
    name: haya14busa
    url: https://github.com/haya14busa
  vimrcs:
    - name: vimrc
      url: https://github.com/haya14busa/dotfiles/blob/be8937e097af4666a4057090b79792acc137fca1/.vimrc
    - name: gvimrc
      url: https://github.com/haya14busa/dotfiles/blob/be8937e097af4666a4057090b79792acc137fca1/.gvimrc
  part: 後編
  members:
    - haya14busa
    - decochan
  log: http://lingr.com/room/vim/archives/2014/02/15#message-18358061
  links:
  other:
```

rubyでyaml読んだり、githubから情報をとってこれると聞いたので、`_data/next.yml`から基本の情報をとってきてGitHubから開催時点のsha-1ハッシュを取得して良い感じにできれば良さげかなと思いまする。

`_data/next.yml` は現在こんなかんじです。

```
- id: 86
  date: 2014-02-22 23:00
  author:
    name: haya14busa
    url: https://github.com/haya14busa
  vimrcs:
    - name: vimrc
      url: https://github.com/haya14busa/dotfiles/blob/master/.vimrc
      hash: be8937e097af4666a4057090b79792acc137fca1
    - name: gvimrc # 分割vimrcも対応
      url: https://github.com/haya14busa/dotfiles/blob/master/.gvimrc
      hash: # 省略可,前後半に分けていて前半のhashでやりたいときなどにオプションでつけれる
  part: 後編 # 省略可
  other: # その他何か特記事項があればここにかける
```

ついでにテキストは以下のようになれば良いのかなと思いました。これをlingr-botから全部生成するのか、それとも
`=== 第84回 vimrc読書会 ===`に反応させているところだけbotに任せるかとかはどうするかわからないのでお任せしますが。

```
=== 第84回 vimrc読書会 ===
- 途中参加/途中離脱OK。声をかける必要はありません
- 読む順はとくに決めないので、好きなように読んで好きなように発言しましょう
- vimrc 内の特定位置を参照する場合は行番号で L100 のように指定します
- 特定の相手に発言/返事する場合は先頭に username: を付けます
- 一通り読み終わったら、読み終わったことを宣言してください。終了の目安にします
- ただの目安なので、宣言してからでも読み返して全然OKです
- 今回は前後半の前半です。終了時間になったら、途中でも強制終了します
本日のvimrc:
  - https://github.com/haya14busa/dotfiles/blob/be8937e097af4666a4057090b79792acc137fca1/.vimrc
  - https://github.com/haya14busa/dotfiles/blob/be8937e097af4666a4057090b79792acc137fca1/.gvimrc
DL用リンク:
  - https://raw.github.com/haya14busa/dotfiles/be8937e097af4666a4057090b79792acc137fca1/.vimrc
  - https://raw.github.com/haya14busa/dotfiles/be8937e097af4666a4057090b79792acc137fca1/.gvimrc
```
